// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApFHmjGudb_Bc0MrTWcWC1zbRP1QEt_zE',
    appId: '1:928528421197:web:9c8b4a65ea0fd1353a2704',
    messagingSenderId: '928528421197',
    projectId: 'ecom-skill-karan-2026',
    authDomain: 'ecom-skill-karan-2026.firebaseapp.com',
    storageBucket: 'ecom-skill-karan-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe56BuRraCEpSXzt0yQIRMkXSbk0Q48-g',
    appId: '1:928528421197:android:f17578f99ae0a39a3a2704',
    messagingSenderId: '928528421197',
    projectId: 'ecom-skill-karan-2026',
    storageBucket: 'ecom-skill-karan-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKR2tRidjIGsSBO6xBzpy57PZTzMCans',
    appId: '1:928528421197:ios:d1e78f4347ea137a3a2704',
    messagingSenderId: '928528421197',
    projectId: 'ecom-skill-karan-2026',
    storageBucket: 'ecom-skill-karan-2026.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZKR2tRidjIGsSBO6xBzpy57PZTzMCans',
    appId: '1:928528421197:ios:d1e78f4347ea137a3a2704',
    messagingSenderId: '928528421197',
    projectId: 'ecom-skill-karan-2026',
    storageBucket: 'ecom-skill-karan-2026.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApFHmjGudb_Bc0MrTWcWC1zbRP1QEt_zE',
    appId: '1:928528421197:web:a5991e4851d4d2b03a2704',
    messagingSenderId: '928528421197',
    projectId: 'ecom-skill-karan-2026',
    authDomain: 'ecom-skill-karan-2026.firebaseapp.com',
    storageBucket: 'ecom-skill-karan-2026.firebasestorage.app',
  );
}
