// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-valJIvynF2ZJJcNdojih8xUTMruvWPY',
    appId: '1:282984146836:web:582a099fc0809296f8d181',
    messagingSenderId: '282984146836',
    projectId: 'ecom-750fc',
    authDomain: 'ecom-750fc.firebaseapp.com',
    storageBucket: 'ecom-750fc.firebasestorage.app',
    measurementId: 'G-1GS6RENG56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt0r928tO1TtV_oKgumGCFsTe3jotk6Q0',
    appId: '1:282984146836:android:b2e0fc2653b1c62ff8d181',
    messagingSenderId: '282984146836',
    projectId: 'ecom-750fc',
    storageBucket: 'ecom-750fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBvu-vLUawrJWPVSqchNaRniMeau57UAI',
    appId: '1:282984146836:ios:f64b9431ca75e522f8d181',
    messagingSenderId: '282984146836',
    projectId: 'ecom-750fc',
    storageBucket: 'ecom-750fc.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBvu-vLUawrJWPVSqchNaRniMeau57UAI',
    appId: '1:282984146836:ios:f64b9431ca75e522f8d181',
    messagingSenderId: '282984146836',
    projectId: 'ecom-750fc',
    storageBucket: 'ecom-750fc.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-valJIvynF2ZJJcNdojih8xUTMruvWPY',
    appId: '1:282984146836:web:bc6cefa9e1b25ff0f8d181',
    messagingSenderId: '282984146836',
    projectId: 'ecom-750fc',
    authDomain: 'ecom-750fc.firebaseapp.com',
    storageBucket: 'ecom-750fc.firebasestorage.app',
    measurementId: 'G-YXX580BH6J',
  );
}
